name: CI and Publish

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish (or "all")'
        required: true
        type: choice
        options:
          - all
          - glin-types
          - glin-client
          - glin-contracts
          - glin-indexer
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: read

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Stage 1: Quality Checks (always runs)
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check documentation
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # Stage 2: Detect Changes (only on main branch pushes)
  detect-changes:
    name: Detect Changed Packages
    needs: [fmt, clippy, test, docs, security-audit]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      changed_packages: ${{ steps.detect.outputs.packages }}
      should_publish: ${{ steps.detect.outputs.should_publish }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed packages
        id: detect
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.package }}" = "all" ]; then
              echo "packages=[\"glin-types\",\"glin-client\",\"glin-contracts\",\"glin-indexer\"]" >> $GITHUB_OUTPUT
            else
              echo "packages=[\"${{ inputs.package }}\"]" >> $GITHUB_OUTPUT
            fi
            echo "should_publish=true" >> $GITHUB_OUTPUT
          else
            # Detect changes from last commit
            CHANGED_PACKAGES=$(git diff --name-only HEAD~1 HEAD | grep -E '^(glin-types|glin-client|glin-contracts|glin-indexer)/' | cut -d'/' -f1 | sort -u | jq -R -s -c 'split("\n")[:-1]')

            if [ "$CHANGED_PACKAGES" = "[]" ] || [ -z "$CHANGED_PACKAGES" ]; then
              echo "No package changes detected"
              echo "packages=[]" >> $GITHUB_OUTPUT
              echo "should_publish=false" >> $GITHUB_OUTPUT
            else
              echo "Changed packages: $CHANGED_PACKAGES"
              echo "packages=$CHANGED_PACKAGES" >> $GITHUB_OUTPUT
              echo "should_publish=true" >> $GITHUB_OUTPUT
            fi
          fi

  # Stage 3: Version and Publish (only after ALL checks pass)
  version-and-publish:
    name: Version and Publish ${{ matrix.package }}
    needs: [detect-changes]
    if: needs.detect-changes.outputs.should_publish == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-changes.outputs.changed_packages) }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine version bump
        id: version
        run: |
          BUMP_TYPE="${{ inputs.version_bump }}"
          if [ -z "$BUMP_TYPE" ]; then
            # Auto-detect from commit message
            COMMIT_MSG=$(git log -1 --pretty=%B)
            if echo "$COMMIT_MSG" | grep -iE "^(breaking|major):"; then
              BUMP_TYPE="major"
            elif echo "$COMMIT_MSG" | grep -iE "^(feat|feature|minor):"; then
              BUMP_TYPE="minor"
            else
              BUMP_TYPE="patch"
            fi
          fi
          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
          echo "Detected version bump: $BUMP_TYPE"

      - name: Get current version
        id: current_version
        run: |
          cd ${{ matrix.package }}
          CURRENT_VERSION=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Bump version
        id: new_version
        run: |
          cd ${{ matrix.package }}

          # Bump version
          cargo set-version --bump ${{ steps.version.outputs.bump_type }}

          # Get new version
          NEW_VERSION=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

          # Update workspace version in root Cargo.toml
          cd ..
          sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" Cargo.toml

      - name: Update dependent package versions
        run: |
          NEW_VERSION="${{ steps.new_version.outputs.version }}"
          PACKAGE="${{ matrix.package }}"

          echo "Updating dependencies for $PACKAGE to $NEW_VERSION"

          # Update dependencies in other packages
          for PKG_DIR in glin-types glin-client glin-contracts glin-indexer; do
            if [ "$PKG_DIR" != "$PACKAGE" ] && [ -f "$PKG_DIR/Cargo.toml" ]; then
              sed -i "s/^$PACKAGE = { version = \"[^\"]*\"/$PACKAGE = { version = \"$NEW_VERSION\"/" "$PKG_DIR/Cargo.toml"
            fi
          done

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd ${{ matrix.package }}
          cargo publish --token $CARGO_REGISTRY_TOKEN --allow-dirty

      - name: Commit version bump
        run: |
          git add .
          git commit -m "chore: bump ${{ matrix.package }} to v${{ steps.new_version.outputs.version }}"
          git push

      - name: Create Git tag
        run: |
          TAG="${{ matrix.package }}-v${{ steps.new_version.outputs.version }}"
          git tag -a "$TAG" -m "Release ${{ matrix.package }} v${{ steps.new_version.outputs.version }}"
          git push origin "$TAG"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package }}-v${{ steps.new_version.outputs.version }}
          release_name: ${{ matrix.package }} v${{ steps.new_version.outputs.version }}
          body: |
            ## Changes in ${{ matrix.package }} v${{ steps.new_version.outputs.version }}

            Bumped from v${{ steps.current_version.outputs.version }} to v${{ steps.new_version.outputs.version }} (${{ steps.version.outputs.bump_type }})

            Published from commit ${{ github.sha }}

            ### Installation
            ```toml
            ${{ matrix.package }} = "${{ steps.new_version.outputs.version }}"
            ```
          draft: false
          prerelease: false
